# Generated by Django 4.2 on 2023-04-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muid', models.CharField(default='', max_length=50)),
                ('uid', models.CharField(default='', max_length=50)),
                ('content', models.CharField(default='', max_length=100)),
                ('timestamp', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
