# Generated by Django 4.2 on 2023-04-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=11)),
                ('gender', models.IntegerField(default=0)),
                ('isActive', models.IntegerField(default=1)),
                ('role', models.IntegerField(default=0)),
                ('avator', models.ImageField(default='static/avator/default.png', upload_to='avator')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
